name: Sample_BRE_Demo_Ruleset
description: Ruleset that contains business rule to be applied in Sample_BRE_Demo.
version: '1.8'
author: nathan+demo2@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: samplebredemoruleset
  parentArtefactID: nathandais2024prophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2025-01-08 09:54:57'
pipelines:
  pipelines/Test:
    name: Test
    description: ''
    author: nathan+demo2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-01-08 09:54:57'
    datasets:
      inputs: []
      outputs: []
    subgraphs: []
    dependencies: {}
datasets: {}
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-01-08 09:54:57'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules:
    businessRules/PromoCodeRule:
      name: PromoCodeRule
      description: Create promo offers for customers based on spend amount and recency
        of latest purchase
      tags: []
      inputs: []
      outputs: []
      author: nathan+demo2@prophecy.io
      createdAt: '2022-12-15 18:04:50'
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2025-01-08T09:54:57.160835Z'
  name: plibMaven
  version: 8.6.0
  id: '112206751'
  createdAt: '2025-01-08T09:54:57.160835Z'
  type: plibMaven
- modifiedAt: '2025-01-08T09:54:57.160835Z'
  name: plibPypi
  version: 1.9.28
  id: '661473917'
  createdAt: '2025-01-08T09:54:57.160835Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.39
    isDefault: true
    author: null
    createdAt: '2025-01-08 09:54:45'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2025-01-08 09:54:45'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
