name: Sample_BRE
description: Sample BRE Project using some business rules on sample Databricks Data.
version: '1.0'
author: nathan+demo2@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: samplebre
  parentArtefactID: nathandais2024prophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2025-01-07 23:50:03'
pipelines:
  pipelines/Sample_BRE_Pipeline:
    name: L1_Sample_BRE_Pipeline
    description: Analyzes customer and order data to compute total revenue per customer.
      It joins customer details with their respective orders, identifies recent orders,
      and determines high-value customers. The pipeline also applies promotional rules,
      enhancing customer insights for targeted marketing strategies.
    author: nathan+demo2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-01-07 23:50:03'
    datasets:
      inputs:
      - datasets/Customer
      - datasets/Orders
      outputs: []
    subgraphs: []
    dependencies: {}
  pipelines/L0_setup_sample_data:
    name: L0_setup_sample_data
    description: ''
    author: nathan+demo2@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2025-01-08 09:19:45'
    datasets:
      inputs: []
      outputs:
      - datasets/Customer
      - datasets/Orders
    subgraphs: []
    dependencies: {}
datasets:
  datasets/Customer:
    name: Customer
    description: ''
    author: nathan+demo2@prophecy.io
    createdAt: '2025-01-08 09:21:37'
    mode: batch
    physicalDatasets:
      DBX_Dev:
        fabricId: 13781
        datasetType: File
        description: ''
        author: nathan+demo2@prophecy.io
        createdAt: '2025-01-08 09:21:37'
  datasets/Orders:
    name: Orders
    description: ''
    author: nathan+demo2@prophecy.io
    createdAt: '2025-01-08 09:22:53'
    mode: batch
    physicalDatasets:
      DBX_Dev:
        fabricId: 13781
        datasetType: File
        description: ''
        author: nathan+demo2@prophecy.io
        createdAt: '2025-01-08 09:22:53'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2025-01-07 23:50:03'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules:
    businessRules/IdentifyRecentOrders:
      name: IdentifyRecentOrders
      description: 'Flag for whether an order is considered a recent order. '
      tags: []
      inputs: []
      outputs: []
      author: nathan+demo2@prophecy.io
      createdAt: '2022-12-15 18:04:50'
    businessRules/IdentifyHighValueCustomers:
      name: IdentifyHighValueCustomers
      description: Identify high value customers based on spending and total order
        amounts.
      tags: []
      inputs: []
      outputs: []
      author: nathan+demo2@prophecy.io
      createdAt: '2022-12-15 18:04:50'
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- type: plibMaven
  modifiedAt: '2025-01-08T08:36:12.114085Z'
  name: plibMaven
  version: 8.6.0
  id: '668559711'
  createdAt: '2025-01-08T08:36:12.114054Z'
- type: plibPypi
  modifiedAt: '2025-01-08T08:36:12.114138Z'
  name: plibPypi
  version: 1.9.28
  id: '1418928384'
  createdAt: '2025-01-08T08:36:12.114128Z'
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.39
    isDefault: true
    author: null
    createdAt: '2025-01-07 23:49:43'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2025-01-07 23:49:43'
  '39483':
    projectUID: 39483
    projectName: Sample_BRE_Demo_Ruleset
    repositoryPath: gitUri=https://github.com/SimpleDataLabsInc/sample_BRE_demo_ruleset&subPath=/
    version: Sample_BRE_Demo_Ruleset/1.7
    isDefault: false
    author: null
    createdAt: '2025-01-08 11:00:57'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
